server:

  port: 443

  servlet:

    context-path: /

  ssl:

    enabled: true

    key-store: classpath:cert.p12

    key-store-type: PKCS12

    key-password: 123456

    key-store-password: 123456